/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./ballot.sol";
export type { ballotSol };
import type * as todoSol from "./todo.sol";
export type { todoSol };
export * as factories from "./factories";
export type { Ballot } from "./ballot.sol/Ballot";
export { Ballot__factory } from "./factories/ballot.sol/Ballot__factory";
export type { Todo } from "./todo.sol/Todo";
export { Todo__factory } from "./factories/todo.sol/Todo__factory";
